### ISSUE TITLE
No "Train Model" button is shown

### ISSUE THREAD

**Issue by payload10** [alexdevassy/Machine_Learning_CTF_Challenges#1]
After uploading the .zip file progress is shown as 100%, but no "Train Model" button is shown
![Uploading Screenshot_2023-11-10_12-46-01.png…]()

**Comment by alexdevassy** [comment]
The screenshot you uploaded is not visible. And it would be helpful if you could mention the steps you have done to get this issue, like what file you have uploaded etc.

**Comment by alexdevassy** [comment]
@payload10 This error was due to "uploads" directory was missing. Have resolved this at [e87aaf3f922a1690457f6652bdda6def10187e86](https://github.com/alexdevassy/Machine_Learning_CTF_Challenges/commit/e87aaf3f922a1690457f6652bdda6def10187e86)

**Comment by payload10** [comment]
Hey, i hope u r doing good.

Thanks, gor the fix!
